deleteSubscriptions:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-deleteSubscriptions
  events:
    - http:
        path: api/v1/subscriptions
        method: DELETE
        cors: true

deleteSubscriptionByUuid:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-deleteSubscriptionByUuid
  events:
    - http:
        path: api/v1/subscriptions/{uuid}
        method: DELETE
        cors: true

downTableSubscription:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-downTableSubscription
  events:
    - http:
        path: api/v1/subscriptions/down
        method: POST
        cors: true

getSubscriptionByUuid:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getSubscriptionByUuid
  events:
    - http:
        path: api/v1/subscriptions/{uuid}
        method: GET
        cors: true

getSubscriptions:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getSubscriptions
  events:
    - http:
        path: api/v1/subscriptions
        method: GET
        cors: true

getSubscriptionsNextPage:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getSubscriptionsNextPage
  events:
    - http:
        path: api/v1/subscriptions/next/{exclusiveStartKey}
        method: GET
        cors: true

putSubscription:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-putSubscription
  events:
    - http:
        path: api/v1/subscriptions
        method: POST
        cors: true

updateSubscription:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-updateSubscription
  events:
    - http:
        path: api/v1/subscriptions
        method: PUT
        cors: true

upTableSubscription:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-upTableSubscription
  events:
    - http:
        path: api/v1/subscriptions/up
        method: POST
        cors: true
