language: node_js
node_js:
  - "8.15.0"
before_install:
  - npm install -g npm
  - cp .env.example .env
install:
  - npm install
script:
  - npm run audit:dependencies
  - npm run test
  - npm run build
