language: node_js
node_js:
  - "8.15.0"
before_install:
  - npm install -g npm
  - npm i -g yarn
  - cp .env.example .env
install:
  - yarn
script:
  - yarn audit:dependencies
  - yarn test
  - yarn build
