deleteUserGroups:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-deleteUserGroups
  events:
    - http:
        path: api/v1/user-groups
        method: DELETE
        cors: true

deleteUserGroupByUuid:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-deleteUserGroupByUuid
  events:
    - http:
        path: api/v1/user-groups/{uuid}
        method: DELETE
        cors: true

downTableUserGroup:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-downTableUserGroup
  events:
    - http:
        path: api/v1/user-groups/down
        method: POST
        cors: true

getUserGroupByUuid:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getUserGroupByUuid
  events:
    - http:
        path: api/v1/user-groups/{uuid}
        method: GET
        cors: true

getUserGroups:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getUserGroups
  events:
    - http:
        path: api/v1/user-groups
        method: GET
        cors: true

getUserGroupsNextPage:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getUserGroupsNextPage
  events:
    - http:
        path: api/v1/user-groups/next/{exclusiveStartKey}
        method: GET
        cors: true

putUserGroup:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-putUserGroup
  events:
    - http:
        path: api/v1/user-groups
        method: POST
        cors: true

updateUserGroup:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-updateUserGroup
  events:
    - http:
        path: api/v1/user-groups
        method: PUT
        cors: true

upTableUserGroup:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-upTableUserGroup
  events:
    - http:
        path: api/v1/user-groups/up
        method: POST
        cors: true
