encodeVideo:
  handler: src/app.encodeVideo
  name: ${self:service}-${self:provider.stage}-encodeVideo
  events:
    - s3:
        bucket: ${env:SERVERLESS_NAME}-${env:AWS_ACCOUNT_ID}-${self:provider.stage}-video-input
        event: s3:ObjectCreated:*

updateMediaAfterConvertIsDone:
  handler: src/app.updateMediaAfterConvertIsDone
  name: ${self:service}-${self:provider.stage}-updateMediaAfterConvertIsDone
  events:
    - sns: arn:aws:sns:${env:AWS_REGION_CODE}:${env:AWS_ACCOUNT_ID}:${self:provider.stage}-updateMediaAfterConvertIsDone
