encodeVideo:
  handler: src/app.encodeVideo
  name: ${self:service}-${self:provider.stage}-encodeVideo
  events:
    - s3:
        bucket: ${env:SERVERLESS_NAME}-${env:AWS_ACCOUNT_ID}-${self:provider.stage}-video-input
        event: s3:ObjectCreated:*

notify:
  handler: src/app.notify
  name: ${self:service}-${self:provider.stage}-notify
  events:
    - sns: arn:aws:sns:${env:AWS_REGION_CODE}:${env:AWS_ACCOUNT_ID}:${self:provider.stage}-notify
